### ISSUE TITLE
scrollview嵌套web或者web作为header的问题

### ISSUE THREAD

**Issue by qq171161636** [youlookwhat/WebViewStudy#11]
当webview外层加了一个scrollview时，我用的您的demo，然后在web外层套了一个scollview，加载的网页是一个纯图片网页，当我点击图片预览的时候就黑屏了（是图片黑屏，再点一退出图片预览），请问一下这个怎么解决？不嵌套都是正常的。 url：http://app.yjzsapp.com/app/wap/article.htm?articleId=fa998902bfaa499f91a7218b88507542。
万分感谢这个怎么解决.

**Comment by youlookwhat** [comment]
scrollview嵌套web暂时没有使用过，不过web作为header我们项目中一直在使用
web作为header，web外面直接使用线性布局包裹即可，不用再使用scrollview包裹，
然后将web作为headerview加入，我这边不会产生问题，使用的是 https://github.com/XRecyclerView/XRecyclerView 然后将web布局作为头布局加入

**Comment by qq171161636** [comment]
作为header这种方法我也试过！不知道是不是我的方法有问题。一般的url地址没问题，像上面我发的那个url里面是多图，点击图片预览就有问题，方便的话可以帮忙测试一下我发的那个URL吗？ 还有一点，header的根布局我是用的线性布局，您是说然后再在web的外层再包裹一层么？

**Comment by youlookwhat** [comment]
这个链接里的图片这么长又数量多，强烈不建议 作为header 加入，建议直接使用web加载，如果一定要作为header加入也可以，但是不要进行点击图片了，如果要点击图片的话建议使用原生的查看图片控件，就是使用原生的activity打开图片的url。这样应该可以避免你的这个问题。

**Comment by youlookwhat** [comment]
还有其他问题吗？我先关了，有问题再开吧
