### ISSUE TITLE
老师能帮我吗？谢谢你。

### ISSUE THREAD

**Issue by 2qq2qq** [youlookwhat/WebViewStudy#13]
我只是想做一个app，实现：
调用一个最简单的网页（不需要上传之类的），然后按返回键不退出，依旧在后台呆着。
按返回键后，表单输入的内容在下次打开这个app时依旧在（类似于微信）。
希望整个app体积不超过10K，在后台不大量耗内存。

我看了老师的文章，没做成功。
老师能帮我吗？谢谢你。

**Comment by youlookwhat** [comment]
客气了，你只需要在Activity里处理按下返回键的操作就好了，按下时使应用退到后台。

**Comment by 2qq2qq** [comment]
老师能帮我做一个吗，我不会，我需要这个app方便自己用。谢谢老师

**Comment by youlookwhat** [comment]
帮你做一个App就有点过了，我可以帮你解决问题，做App会耗费太多时间与精力

**Comment by 2qq2qq** [comment]
用哪个软件做，我有源代码，但是不知道怎么打包成app

**Comment by youlookwhat** [comment]
用AndroidStudio，Android 开发工具

**Comment by 2qq2qq** [comment]
谢谢老师

**Comment by SmallRedSister** [comment]
这个我可以做，找我

**Comment by SmallRedSister** [comment]
QQ：2279833535
