### ISSUE TITLE
心疼作者一下下。

### ISSUE THREAD

**Issue by xtvj** [youlookwhat/WebViewStudy#14]
从另一个项目跳过来的，那个项目改了个名字。代码没怎么看是不是一样。那个作者不回复任何Issues，而且截图都有跟这个项目一样的。。Star都到500多了。哈哈哈。。。。。

**Comment by youlookwhat** [comment]
真的跟无奈。我看到了那个项目，起初连参考出处都没给，后面才在文末加了说明；然后又引入了我优化过的进度条控件，结果把署名都改了，也没给参考说明，我太南了...

**Comment by xtvj** [comment]
我能做的就是给你一个Star，我是在[Android开发技术周报](https://www.androidweekly.cn/android-dev-weekly-issue-250/)的第10条看到那个项目的，建议你去跟站长说一下。
