### ISSUE TITLE
视频问题

### ISSUE THREAD

**Issue by zkylinfeng** [youlookwhat/WebViewStudy#16]
如果视频本来是竖着的，全屏后就自己来回切换，不知道作者有注意到这个问题没

**Comment by youlookwhat** [comment]
懂你的意思，因为全屏是强制横屏的，但是视频的内容是竖屏的。怎么判断是否要横屏，这是个问题

**Comment by alertross** [comment]
我也遇到这个问题， 请问有进展或则思路吗

**Comment by youlookwhat** [comment]
暂时还没有，如果有办法获取到视频的宽高就好了

**Comment by alertross** [comment]
> 暂时还没有，如果有办法获取到视频的宽高就好了

是的 ， 我也是这么想的， 能拿到宽高比就可以判断了 ，我本身是ios开发， 刚接触android  
`            public void onShowCustomView(View view, CustomViewCallback callback) {
`
这里的View getWidth 和 getHeight 居然会闪退， 所以不明白怎么能拿到宽和高， android 的宽高怎么这么难取得呀

**Comment by youlookwhat** [comment]
我刚也试了这里，发现得到的是0，看来这样取不了，Android 获取宽高是不太友好😂

**Comment by lzybilian** [comment]
看代码，这个问题好像还是没有被解决的。后面有其他思路嘛？目前我是发现可以设置为跟随设备感应

**Comment by youlookwhat** [comment]
上面的问题是有些竖屏的视频全屏后被横屏了，因为我不知道视频是横屏的还是竖屏的。

如果是随设备感应，可以达到解决上面的问题吗。

其实应该可以在点击全屏的时候设置一个回调，自己处理需不需要横屏

**Comment by lzybilian** [comment]
是的，这个问题在于无法知道视频是横屏还是竖屏的。设置为跟随设备感应，至少可以解决掉来回切换的问题。我是用的腾讯tbs浏览服务。目前实现的是，1、竖版视频点击全屏时，变为竖版全屏，横置手机时，会先切换横屏，然后退出全屏播放，再切回竖屏。2、横版视频点击全屏时，变为竖版全屏，横置手机时，会切换为横屏，再竖置手机时，会退出全屏切换为竖屏

**Comment by lzybilian** [comment]
所以，我后面应该还是会把方向放在解析video标签，去获取视频数据。然后来处理是强制横屏还是强制竖屏。

**Comment by youlookwhat** [comment]
如果设置`跟随设备感应`，是可以解决当前的这个问题，但是被设置的那个页面在不进行视频播放后也可以进行横竖屏切换了。

我增加了一个方法，可以自己设置横竖屏，应该会更好点：
```
     /**
     * 全屏显示时处理横竖屏。
     * 默认返回false，全屏时为横屏，全屏还原后为竖屏
     * 如果要手动处理，需要返回true！
     *
     * @param isShow 是否显示了全屏视频 ture点击了全屏显示，false全屏视频还原
     */
    public boolean onHandleScreenOrientation(boolean isShow) {
        return false;
    }
```

我代码上传了你再试试~

**Comment by youlookwhat** [comment]
@lzybilian 

具体使用：
```
    private OnTitleProgressCallback onTitleProgressCallback = new OnTitleProgressCallback() {
        @Override
        public void onReceivedTitle(String title) {
            Log.e("---title", title);
            tvGunTitle.setText(title);
        }

        @Override
        public boolean onHandleScreenOrientation(boolean isShow) {
            if (isShow) {
                ByWebViewActivity.this.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
            } else {
                ByWebViewActivity.this.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED);
            }
            return true;
        }
    };
```

**Comment by youlookwhat** [comment]
@lzybilian 可以运行下demo看能否解决你的问题，或者我可以直接发布一版本你下载看看

**Comment by lzybilian** [comment]
> @lzybilian 可以运行下demo看能否解决你的问题，或者我可以直接发布一版本你下载看看

我项目没这个问题，搭载视频的页面hide的时候会强制指定竖屏的

**Comment by youlookwhat** [comment]
噢噢，那后面这个问题目前已经可以得到解决了

**Comment by youlookwhat** [comment]
@zkylinfeng @alertross 
视频的横竖屏问题基本可以解决了，需要升级到`implementation 'com.github.youlookwhat:ByWebView:1.2.1'`

然后在`OnTitleProgressCallback`里实现`onHandleScreenOrientation`自己自定义处理：
```
    private OnTitleProgressCallback onTitleProgressCallback = new OnTitleProgressCallback() {
        @Override
        public void onReceivedTitle(String title) {
            Log.e("---title", title);
            tvGunTitle.setText(title);
        }

        @Override
        public boolean onHandleScreenOrientation(boolean isShow) {
            if (isShow) {
                ByWebViewActivity.this.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
            } else {
                ByWebViewActivity.this.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED);
            }
            return true;
        }
    };
```

前提是预先知道视频是要横屏还是竖屏，感觉最佳做法是，自己实现原生的视频播放页，然后点击的时候调用。

**Comment by lzybilian** [comment]
你好，今天新发现一个现象，当腾讯tbs内核切换成功时，只需处理view全屏即可，腾讯tbs内核已经处理了是否需要切换横屏。

**Comment by youlookwhat** [comment]
没太理解你说的什么意思。它和我这个项目是否有关联？

**Comment by lzybilian** [comment]
> 没太理解你说的什么意思。它和我这个项目是否有关联？

因为我看你项目中有使用腾讯x5  sdk。我说的tbs内核就是x5  SDK

**Comment by youlookwhat** [comment]
你问的意思是，腾讯tbs内核已经处理了视频全屏播放，我这边是不是不用再处理了，是这个意思麽？

**Comment by lzybilian** [comment]
> 你问的意思是，腾讯tbs内核已经处理了视频全屏播放，我这边是不是不用再处理了，是这个意思麽？

是的，但是不知道腾讯内核是如何处理的。SDK混淆过找不到具体代码实现处，没法看到里面的实现细节

**Comment by youlookwhat** [comment]
你怎么使用的腾讯tbs打开的网页，关于这个方法:`webView.setWebChromeClient()`，能贴出来给我看看吗？
我看是不是有继承腾讯的`WebChromeClient`做处理

**Comment by lzybilian** [comment]
> 你怎么使用的腾讯tbs打开的网页，关于这个方法:`webView.setWebChromeClient()`，能贴出来给我看看吗？ 我看是不是有继承腾讯的`WebChromeClient`做处理

是webview直接就是腾讯的sdk中的webview    类为com.tencent.smtt.sdk.WebView

**Comment by youlookwhat** [comment]
那肯定的，不然怎么用腾讯tbs，其他的配置呢

**Comment by lzybilian** [comment]
> 那肯定的，不然怎么用腾讯tbs，其他的配置呢

腾讯的webview设置的WebChromeClient肯定是腾讯包里的WebChromeClient，不然java类都对不上呀。没有什么其他配置了，要保证tbs内核切换成功。      QbSdk.PreInitCallback   onViewInitFinished这个方法看下回调的是不是true。如果不是的话直接卸载重装，或者清除缓存再打开重新初始化。

**Comment by lzybilian** [comment]
> 那肯定的，不然怎么用腾讯tbs，其他的配置呢

腾讯的webview设置的WebChromeClient肯定是腾讯包里的WebChromeClient，不然java类都对不上呀。没有什么其他配置了，要保证tbs内核切换成功。      QbSdk.PreInitCallback   onViewInitFinished这个方法看下回调的是不是true。如果不是的话直接卸载重装，或者清除缓存再打开重新初始化。

**Comment by youlookwhat** [comment]
`webView.setWebChromeClient(new WebChromeClient());`

腾讯包里的`WebChromeClient`直接设置后，全屏的按钮不能被点击，我试过。因为这个是抽象类，可能是需要你自己去实现。
当然tbs内核肯定是初始化成功了。

---
这个问题到此结束吧，这个不在我考虑的范围之内，且和这个项目暂时相关度不大。

**Comment by lzybilian** [comment]
> `webView.setWebChromeClient(new WebChromeClient());`
> 
> 腾讯包里的`WebChromeClient`直接设置后，全屏的按钮不能被点击，我试过。因为这个是抽象类，可能是需要你自己去实现。 当然tbs内核肯定是初始化成功了。
> 
> 这个问题到此结束吧，这个不在我考虑的范围之内，且和这个项目暂时相关度不大。

ok
