### ISSUE TITLE
想要设置自己的WebView 不用自己的webView 

### ISSUE THREAD

**Issue by Para123123** [youlookwhat/WebViewStudy#18]
CoordinatorLayout和webview套用 实现绑定toolbar 有的网页会出滑动的问题 需要设置特别的webView

**Comment by Para123123** [comment]
toolbar联动需要用到 https://github.com/tobiasrohloff/NestedScrollWebView 这个webview 不好设置 请加一下这个功能吧

**Comment by youlookwhat** [comment]
好的，我增加一个可以设置自定义WebView的功能，不过好了以后需要你那边测试一下

**Comment by Para123123** [comment]
`   private NestedScrollWebView mWebView;
        private WebProgress mWebProgress;
 public Builder setWebProgress(@NonNull WebProgress webProgress) {
            this.mWebProgress = webProgress;
            return this;
        }
   public Builder setWebView(NestedScrollWebView mWebView) {
            this.mWebView = mWebView;
            return this;
        }`

**Comment by Para123123** [comment]
`    <me.jingbin.web.NestedScrollWebView
            android:id="@+id/v_nestedscroll_webview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_below="@+id/toolbar_black_back"
            app:layout_behavior="@string/appbar_scrolling_view_behavior"
            android:background="@color/viewBackground" />

        <me.jingbin.web.WebProgress
            android:id="@+id/v_webprogress"
            android:layout_width="match_parent"
            android:layout_height="3dp"
            android:layout_below="@+id/toolbar_black_back" />`

**Comment by Para123123** [comment]
是这样 我更希望我能指定webView控件 也不需要动态添加WebProgress和webView 我可以指定是哪个webProgress和webview
主要是我 app:layout_behavior="@string/appbar_scrolling_view_behavior"  我不知道怎么代码添加，只会写在xml里=，=
感谢

**Comment by youlookwhat** [comment]
恩恩 明白了，我加一下，可以设置xml布局，布局里就只有一个NestedScrollWebView，但是NestedScrollWebView外层是RelativeLayout,不知道会不会有影响

**Comment by Para123123** [comment]
好的 我会测试的 再次感谢

**Comment by youlookwhat** [comment]
可以了，试一试，将包升级为 1.0.1。


注意：布局文件里使用固定的id = by_custom_webview
示例：
```xml
<?xml version="1.0" encoding="utf-8"?>
<WebView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/by_custom_webview"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />

```

代码配置：
```java
byWebView = ByWebView.with(this)
        .setWebParent(container, new LinearLayout.LayoutParams(-1, -1))
        .setCustomWebViewLayout(R.layout.layout_costom_webview) // 设置自定义WebView
        .useWebProgress(ContextCompat.getColor(this, R.color.coloRed))
        .addJavascriptInterface("injectedObject", new MyJavascriptInterface(this))
        .loadUrl(mUrl);
```
地址：https://github.com/youlookwhat/ByWebView/releases/tag/1.0.1

**Comment by Para123123** [comment]
唔 有点不行 联动没效果了

**Comment by Para123123** [comment]
`package me.jingbin.web;

import android.annotation.SuppressLint;
import android.app.Activity;
import android.content.Intent;
import android.content.pm.ActivityInfo;
import android.os.Build;
import android.text.TextUtils;
import android.view.KeyEvent;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.widget.RelativeLayout;

import androidx.annotation.LayoutRes;
import androidx.annotation.NonNull;
import androidx.fragment.app.Fragment;

/**
 * 网页可以处理:
 * 点击相应控件：
 * - 进度条显示
 * - 上传图片(版本兼容)
 * - 全屏播放网络视频
 * - 唤起微信支付宝
 * - 拨打电话、发送短信、发送邮件
 * - 返回网页上一层、显示网页标题
 * JS交互部分：
 * - 前端代码嵌入js(缺乏灵活性)
 * - 网页自带js跳转
 *
 * @author jingbin
 * link to https://github.com/youlookwhat/ByWebView
 */
public class ByWebView {

    private NestedScrollWebView mWebView;
    private WebProgress mProgressBar;
    private View mErrorView;
    private int mErrorLayoutId;
    private String mErrorTitle;
    private Activity activity;
    private ByWebChromeClient mWebChromeClient;
    private ByLoadJsHolder byLoadJsHolder;

    private ByWebView(Builder builder) {
        this.activity = builder.mActivity;
        this.mErrorTitle = builder.mErrorTitle;
        this.mErrorLayoutId = builder.mErrorLayoutId;

        if (null == builder.mWebView) {

        }
        mWebView = builder.mWebView;
        // 进度条布局
        handleWebProgress(builder);
        // 配置
        handleSetting();
        // 视频、照片、进度条
        mWebChromeClient = new ByWebChromeClient(activity, this);
        mWebChromeClient.setOnByWebChromeCallback(builder.mOnTitleProgressCallback);
        mWebView.setWebChromeClient(mWebChromeClient);

        // 错误页面、页面结束、处理DeepLink
        ByWebViewClient mByWebViewClient = new ByWebViewClient(activity, this);
        mByWebViewClient.setOnByWebClientCallback(builder.mOnByWebClientCallback);
        mWebView.setWebViewClient(mByWebViewClient);

        handleJsInterface(builder);
    }

    @SuppressLint({"JavascriptInterface", "AddJavascriptInterface"})
    private void handleJsInterface(Builder builder) {
        if (!TextUtils.isEmpty(builder.mInterfaceName) && builder.mInterfaceObj != null) {
            mWebView.addJavascriptInterface(builder.mInterfaceObj, builder.mInterfaceName);
        }
    }

    public ByLoadJsHolder getLoadJsHolder() {
        if (byLoadJsHolder == null) {
            byLoadJsHolder = new ByLoadJsHolder(mWebView);
        }
        return byLoadJsHolder;
    }

    @SuppressLint("SetJavaScriptEnabled")
    private void handleSetting() {
        WebSettings ws = mWebView.getSettings();
        // 保存表单数据
        ws.setSaveFormData(true);
        // 是否应该支持使用其屏幕缩放控件和手势缩放
        ws.setSupportZoom(true);
        ws.setBuiltInZoomControls(true);
        ws.setDisplayZoomControls(false);
        // 启动应用缓存
        ws.setAppCacheEnabled(true);
        // 设置缓存模式
        ws.setCacheMode(WebSettings.LOAD_DEFAULT);
        // setDefaultZoom  api19被弃用
        // 网页内容的宽度自适应屏幕
        ws.setLoadWithOverviewMode(true);
        ws.setUseWideViewPort(true);
        // 告诉WebView启用JavaScript执行。默认的是false。
        ws.setJavaScriptEnabled(true);
        //  页面加载好以后，再放开图片
        ws.setBlockNetworkImage(false);
        // 使用localStorage则必须打开
        ws.setDomStorageEnabled(true);
        // 排版适应屏幕
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
            ws.setLayoutAlgorithm(WebSettings.LayoutAlgorithm.NARROW_COLUMNS);
        } else {
            ws.setLayoutAlgorithm(WebSettings.LayoutAlgorithm.NORMAL);
        }
        // WebView是否新窗口打开(加了后可能打不开网页)
//        ws.setSupportMultipleWindows(true);

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            // WebView从5.0开始默认不允许混合模式,https中不能加载http资源,需要设置开启。
            ws.setMixedContentMode(WebSettings.MIXED_CONTENT_ALWAYS_ALLOW);
        }
    }

    /**
     * 设置字体默认缩放大小(改变网页字体大小,setTextSize  api14被弃用)
     *
     * @param textZoom 默认100
     */
    public void setTextZoom(int textZoom) {
        mWebView.getSettings().setTextZoom(textZoom);
    }

    private void handleWebProgress(Builder builder) {
        if (builder.mUseWebProgress && null != builder.mWebProgress) {
            mProgressBar = builder.mWebProgress;
            if (builder.mProgressStartColor != 0 && builder.mProgressEndColor != 0) {
                mProgressBar.setColor(builder.mProgressStartColor, builder.mProgressEndColor);
            } else if (builder.mProgressStartColor != 0) {
                mProgressBar.setColor(builder.mProgressStartColor, builder.mProgressStartColor);
            } else if (!TextUtils.isEmpty(builder.mProgressStartColorString)
                    && !TextUtils.isEmpty(builder.mProgressEndColorString)) {
                mProgressBar.setColor(builder.mProgressStartColorString, builder.mProgressEndColorString);
            } else if (!TextUtils.isEmpty(builder.mProgressStartColorString)
                    && TextUtils.isEmpty(builder.mProgressEndColorString)) {
                mProgressBar.setColor(builder.mProgressStartColorString, builder.mProgressStartColorString);
            }
            if (builder.mProgressHeightDp != 0) {
                mProgressBar.setHeight(builder.mProgressHeightDp);
            }
            mProgressBar.setVisibility(View.GONE);
        }
    }

    public void loadUrl(String url) {
        if (!TextUtils.isEmpty(url) && url.endsWith("mp4") && Build.VERSION.SDK_INT <= Build.VERSION_CODES.LOLLIPOP_MR1) {
            mWebView.loadData(ByWebTools.getVideoHtmlBody(url), "text/html", "UTF-8");
        } else {
            mWebView.loadUrl(url);
        }
        if (mProgressBar != null) {
            mProgressBar.show();
        }
        hideErrorView();
    }

    public void reload() {
        hideErrorView();
        mWebView.reload();
    }

    public void onResume() {
        mWebView.onResume();
        // 支付宝网页版在打开文章详情之后,无法点击按钮下一步
        mWebView.resumeTimers();
    }

    public void onPause() {
        mWebView.onPause();
        mWebView.resumeTimers();
    }

    public void onDestroy() {
        if (mWebChromeClient != null && mWebChromeClient.getVideoFullView() != null) {
            mWebChromeClient.getVideoFullView().removeAllViews();
        }
        if (mWebView != null) {
            ViewGroup parent = (ViewGroup) mWebView.getParent();
            if (parent != null) {
                parent.removeView(mWebView);
            }
            mWebView.removeAllViews();
            mWebView.loadDataWithBaseURL(null, "", "text/html", "utf-8", null);
            mWebView.stopLoading();
            mWebView.setWebChromeClient(null);
            mWebView.setWebViewClient(null);
            mWebView.destroy();
            mWebView = null;
        }
    }

    /**
     * 选择图片之后的回调，在Activity里onActivityResult调用
     */
    public void handleFileChooser(int requestCode, int resultCode, Intent intent) {
        if (mWebChromeClient != null) {
            mWebChromeClient.handleFileChooser(requestCode, resultCode, intent);
        }
    }

    public boolean handleKeyEvent(int keyCode, KeyEvent event) {
        if (keyCode == KeyEvent.KEYCODE_BACK) {
            return isBack();
        }
        return false;
    }

    @SuppressLint("SourceLockedOrientationActivity")
    public boolean isBack() {
        // 全屏播放退出全屏
        if (mWebChromeClient.inCustomView()) {
            mWebChromeClient.onHideCustomView();
            if (activity != null) {
                activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
            }
            return true;

            // 返回网页上一页
        } else if (mWebView.canGoBack()) {
            hideErrorView();
            mWebView.goBack();
            return true;
        }
        return false;
    }

    public WebView getWebView() {
        return mWebView;
    }

    public WebProgress getProgressBar() {
        return mProgressBar;
    }

    /**
     * 显示错误布局
     */
    public void showErrorView() {
        try {
            if (mErrorView == null) {
                RelativeLayout parent = (RelativeLayout) mWebView.getParent();
                mErrorView = LayoutInflater.from(parent.getContext()).inflate((mErrorLayoutId == 0) ? R.layout.by_load_url_error : mErrorLayoutId, null);
                mErrorView.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        reload();
                    }
                });
                parent.addView(mErrorView, new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
            } else {
                mErrorView.setVisibility(View.VISIBLE);
            }
            mWebView.setVisibility(View.INVISIBLE);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * 隐藏错误布局
     */
    public void hideErrorView() {
        if (mErrorView != null) {
            mErrorView.setVisibility(View.GONE);
        }
    }

    public View getErrorView() {
        return mErrorView;
    }

    String getErrorTitle() {
        return mErrorTitle;
    }

    public static Builder with(@NonNull Activity activity) {
        if (activity == null) {
            throw new NullPointerException("activity can not be null .");
        }
        return new Builder(activity);
    }


    public static class Builder {
        private Activity mActivity;
        private Fragment mFragment;
        // 默认使用进度条
        private boolean mUseWebProgress = true;
        // 进度条 开始颜色
        private int mProgressStartColor;
        private String mProgressStartColorString;
        // 进度条 结束颜色
        private int mProgressEndColor;
        private String mProgressEndColorString;
        // 进度条 高度
        private int mProgressHeightDp;
        private int mErrorLayoutId;
        private String mErrorTitle;
        private String mInterfaceName;
        private Object mInterfaceObj;
        private OnTitleProgressCallback mOnTitleProgressCallback;
        private OnByWebClientCallback mOnByWebClientCallback;

        private NestedScrollWebView mWebView;
        private WebProgress mWebProgress;

        public Builder(Activity activity) {
            this.mActivity = activity;
        }

        public Builder(Activity activity, Fragment fragment) {
            this.mActivity = activity;
            this.mFragment = fragment;
        }

        public Builder setWebProgress(@NonNull WebProgress webProgress) {
            this.mWebProgress = webProgress;
            return this;
        }

        /**
         * @param isUse 是否使用进度条，默认true
         */
        public Builder useWebProgress(boolean isUse) {
            this.mUseWebProgress = isUse;
            return this;
        }

        /**
         * 设置进度条颜色
         *
         * @param color 示例：ContextCompat.getColor(this, R.color.red)
         */
        public Builder useWebProgress(int color) {
            return useWebProgress(color, color, 3);
        }

        /**
         * 设置进度条颜色
         *
         * @param color 示例："#FF0000"
         */
        public Builder useWebProgress(String color) {
            return useWebProgress(color, color, 3);
        }

        /**
         * 设置进度条渐变色颜色
         *
         * @param startColor 开始颜色
         * @param endColor   结束颜色
         * @param heightDp   进度条高度，单位dp
         */
        public Builder useWebProgress(int startColor, int endColor, int heightDp) {
            mProgressStartColor = startColor;
            mProgressEndColor = endColor;
            mProgressHeightDp = heightDp;
            return this;
        }

        public Builder useWebProgress(String startColor, String endColor, int heightDp) {
            mProgressStartColorString = startColor;
            mProgressEndColorString = endColor;
            mProgressHeightDp = heightDp;
            return this;
        }

        /**
         * @param errorLayoutId 错误页面布局，标题默认“网页打开失败”
         */
        public Builder setErrorLayout(@LayoutRes int errorLayoutId) {
            mErrorLayoutId = errorLayoutId;
            return this;
        }

        /**
         * @param errorLayoutId 错误页面布局
         * @param errorTitle    错误页面标题
         */
        public Builder setErrorLayout(@LayoutRes int errorLayoutId, String errorTitle) {
            mErrorLayoutId = errorLayoutId;
            mErrorTitle = errorTitle;
            return this;
        }

        /**
         * 添加Js监听
         */
        public Builder addJavascriptInterface(String interfaceName, Object interfaceObj) {
            this.mInterfaceName = interfaceName;
            this.mInterfaceObj = interfaceObj;
            return this;
        }

        /**
         * @param onTitleProgressCallback 返回Title 和 Progress
         */
        public Builder setOnTitleProgressCallback(OnTitleProgressCallback onTitleProgressCallback) {
            this.mOnTitleProgressCallback = onTitleProgressCallback;
            return this;
        }

        /**
         * 页面加载结束监听 和 处理三方跳转链接
         */
        public Builder setOnByWebClientCallback(OnByWebClientCallback onByWebClientCallback) {
            this.mOnByWebClientCallback = onByWebClientCallback;
            return this;
        }

        public Builder setWebView(NestedScrollWebView mWebView) {
            this.mWebView = mWebView;
            return this;
        }


        public ByWebView loadUrl(String url) {
            ByWebView byWebView = new ByWebView(this);
            byWebView.loadUrl(url);
            return byWebView;
        }
    }

}
`

**Comment by Para123123** [comment]
` public static class Builder {
        private Activity mActivity;
        private Fragment mFragment;
        // 默认使用进度条
        private boolean mUseWebProgress = true;
        // 进度条 开始颜色
        private int mProgressStartColor;
        private String mProgressStartColorString;
        // 进度条 结束颜色
        private int mProgressEndColor;
        private String mProgressEndColorString;
        // 进度条 高度
        private int mProgressHeightDp;
        private int mErrorLayoutId;
        private String mErrorTitle;
        private String mInterfaceName;
        private Object mInterfaceObj;
        private OnTitleProgressCallback mOnTitleProgressCallback;
        private OnByWebClientCallback mOnByWebClientCallback;

        private NestedScrollWebView mWebView;
        private WebProgress mWebProgress;

        public Builder(Activity activity) {
            this.mActivity = activity;
        }

        public Builder(Activity activity, Fragment fragment) {
            this.mActivity = activity;
            this.mFragment = fragment;
        }

        public Builder setWebProgress(@NonNull WebProgress webProgress) {
            this.mWebProgress = webProgress;
            return this;
        }

        /**
         * @param isUse 是否使用进度条，默认true
         */
        public Builder useWebProgress(boolean isUse) {
            this.mUseWebProgress = isUse;
            return this;
        }

        /**
         * 设置进度条颜色
         *
         * @param color 示例：ContextCompat.getColor(this, R.color.red)
         */
        public Builder useWebProgress(int color) {
            return useWebProgress(color, color, 3);
        }

        /**
         * 设置进度条颜色
         *
         * @param color 示例："#FF0000"
         */
        public Builder useWebProgress(String color) {
            return useWebProgress(color, color, 3);
        }

        /**
         * 设置进度条渐变色颜色
         *
         * @param startColor 开始颜色
         * @param endColor   结束颜色
         * @param heightDp   进度条高度，单位dp
         */
        public Builder useWebProgress(int startColor, int endColor, int heightDp) {
            mProgressStartColor = startColor;
            mProgressEndColor = endColor;
            mProgressHeightDp = heightDp;
            return this;
        }

        public Builder useWebProgress(String startColor, String endColor, int heightDp) {
            mProgressStartColorString = startColor;
            mProgressEndColorString = endColor;
            mProgressHeightDp = heightDp;
            return this;
        }

        /**
         * @param errorLayoutId 错误页面布局，标题默认“网页打开失败”
         */
        public Builder setErrorLayout(@LayoutRes int errorLayoutId) {
            mErrorLayoutId = errorLayoutId;
            return this;
        }

        /**
         * @param errorLayoutId 错误页面布局
         * @param errorTitle    错误页面标题
         */
        public Builder setErrorLayout(@LayoutRes int errorLayoutId, String errorTitle) {
            mErrorLayoutId = errorLayoutId;
            mErrorTitle = errorTitle;
            return this;
        }

        /**
         * 添加Js监听
         */
        public Builder addJavascriptInterface(String interfaceName, Object interfaceObj) {
            this.mInterfaceName = interfaceName;
            this.mInterfaceObj = interfaceObj;
            return this;
        }

        /**
         * @param onTitleProgressCallback 返回Title 和 Progress
         */
        public Builder setOnTitleProgressCallback(OnTitleProgressCallback onTitleProgressCallback) {
            this.mOnTitleProgressCallback = onTitleProgressCallback;
            return this;
        }

        /**
         * 页面加载结束监听 和 处理三方跳转链接
         */
        public Builder setOnByWebClientCallback(OnByWebClientCallback onByWebClientCallback) {
            this.mOnByWebClientCallback = onByWebClientCallback;
            return this;
        }

        public Builder setWebView(NestedScrollWebView mWebView) {
            this.mWebView = mWebView;
            return this;
        }


        public ByWebView loadUrl(String url) {
            ByWebView byWebView = new ByWebView(this);
            byWebView.loadUrl(url);
            return byWebView;
        }
    }`

**Comment by Para123123** [comment]
` private ByWebView(Builder builder) {
        this.activity = builder.mActivity;
        this.mErrorTitle = builder.mErrorTitle;
        this.mErrorLayoutId = builder.mErrorLayoutId;

        if (null == builder.mWebView) {

        }
        mWebView = builder.mWebView;
        // 进度条布局
        handleWebProgress(builder);
        // 配置
        handleSetting();
        // 视频、照片、进度条
        mWebChromeClient = new ByWebChromeClient(activity, this);
        mWebChromeClient.setOnByWebChromeCallback(builder.mOnTitleProgressCallback);
        mWebView.setWebChromeClient(mWebChromeClient);

        // 错误页面、页面结束、处理DeepLink
        ByWebViewClient mByWebViewClient = new ByWebViewClient(activity, this);
        mByWebViewClient.setOnByWebClientCallback(builder.mOnByWebClientCallback);
        mWebView.setWebViewClient(mByWebViewClient);

        handleJsInterface(builder);
    }`

**Comment by Para123123** [comment]
`  
private void handleWebProgress(Builder builder) {
        if (builder.mUseWebProgress && null != builder.mWebProgress) {
            mProgressBar = builder.mWebProgress;
            if (builder.mProgressStartColor != 0 && builder.mProgressEndColor != 0) {
                mProgressBar.setColor(builder.mProgressStartColor, builder.mProgressEndColor);
            } else if (builder.mProgressStartColor != 0) {
                mProgressBar.setColor(builder.mProgressStartColor, builder.mProgressStartColor);
            } else if (!TextUtils.isEmpty(builder.mProgressStartColorString)
                    && !TextUtils.isEmpty(builder.mProgressEndColorString)) {
                mProgressBar.setColor(builder.mProgressStartColorString, builder.mProgressEndColorString);
            } else if (!TextUtils.isEmpty(builder.mProgressStartColorString)
                    && TextUtils.isEmpty(builder.mProgressEndColorString)) {
                mProgressBar.setColor(builder.mProgressStartColorString, builder.mProgressStartColorString);
            }
            if (builder.mProgressHeightDp != 0) {
                mProgressBar.setHeight(builder.mProgressHeightDp);
            }
            mProgressBar.setVisibility(View.GONE);
        }
    }`

**Comment by Para123123** [comment]
`private void handleWebProgress(Builder builder) {
        if (builder.mUseWebProgress && null != builder.mWebProgress) {
            mProgressBar = builder.mWebProgress;
            if (builder.mProgressStartColor != 0 && builder.mProgressEndColor != 0) {
                mProgressBar.setColor(builder.mProgressStartColor, builder.mProgressEndColor);
            } else if (builder.mProgressStartColor != 0) {
                mProgressBar.setColor(builder.mProgressStartColor, builder.mProgressStartColor);
            } else if (!TextUtils.isEmpty(builder.mProgressStartColorString)
                    && !TextUtils.isEmpty(builder.mProgressEndColorString)) {
                mProgressBar.setColor(builder.mProgressStartColorString, builder.mProgressEndColorString);
            } else if (!TextUtils.isEmpty(builder.mProgressStartColorString)
                    && TextUtils.isEmpty(builder.mProgressEndColorString)) {
                mProgressBar.setColor(builder.mProgressStartColorString, builder.mProgressStartColorString);
            }
            if (builder.mProgressHeightDp != 0) {
                mProgressBar.setHeight(builder.mProgressHeightDp);
            }
            mProgressBar.setVisibility(View.GONE);
        }
    }`

**Comment by youlookwhat** [comment]
因为外面包了一层RelativeLayout，而app:layout_behavior="@string/appbar_scrolling_view_behavior"应该在RelativeLayout上的。建议你分开使用吧。。

你是用的最新的包吗？implementation 'com.github.youlookwhat:ByWebView:1.0.1'

**Comment by Para123123** [comment]
public static class Builder {

**Comment by Para123123** [comment]
` public static class Builder {`

**Comment by Para123123** [comment]
public static class Builder {   
private NestedScrollWebView mWebView;
        private WebProgress mWebProgress;
}

我是这样添加的 就有效果了 自己制定webView和progress

**Comment by youlookwhat** [comment]
直接改的源码呀，可以用了就好

**Comment by Para123123** [comment]
=，= 经理说以后还要跟着你更新的 所以希望你能支持一下这个功能

**Comment by youlookwhat** [comment]
我看你的意思是直接把源码拷过去改的呀，😂

**Comment by Para123123** [comment]
我这边是这么改先用起来的,你支持这个功能的话 我就不用载下来了，以后你更新我也不用再载下来改了

**Comment by youlookwhat** [comment]
可以。你把你根布局的xml发给我看看，还有你设置ByWebView的位置，我要改了自己试一下

**Comment by Para123123** [comment]
` ByWebView
            .with(activity)
            .setWebView(binding.vNestedscrollWebview)
            .setWebProgress(binding.vWebprogress)
            .useWebProgress(true)`

**Comment by Para123123** [comment]
` <androidx.coordinatorlayout.widget.CoordinatorLayout
        android:id="@+id/Coord"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.google.android.material.appbar.AppBarLayout
            style="@style/ActionBar"
            android:layout_width="match_parent"
            android:layout_height="@dimen/bar_height">

            <androidx.appcompat.widget.Toolbar
                android:id="@+id/toolbar"
                style="@style/ActionBar"
                android:layout_width="match_parent"
                android:layout_height="@dimen/bar_height"
                app:contentInsetStart="0dp"
                app:layout_scrollFlags="scroll|enterAlways">

                <include
                    layout="@layout/layout_topbar_img"
                    app:viewModel="@{viewModel}" />
            </androidx.appcompat.widget.Toolbar>
        </com.google.android.material.appbar.AppBarLayout>


        <me.jingbin.web.NestedScrollWebView
            android:id="@+id/v_nestedscroll_webview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior" />
        <me.jingbin.web.WebProgress
            android:id="@+id/v_webprogress"
            android:layout_width="match_parent"
            android:layout_height="3dp"
            android:layout_below="@+id/toolbar_black_back" />
    </androidx.coordinatorlayout.widget.CoordinatorLayout>
`

**Comment by Para123123** [comment]
WebProgress是其他地方移过来的 xml会报错 这个我可以自己找地方放置就行了 可以忽略WebProgress

**Comment by youlookwhat** [comment]
好的👌，我试试

**Comment by youlookwhat** [comment]
@Para123123 
修改了一下，你可以试试
升级为：`implementation 'com.github.youlookwhat:ByWebView:1.1.0`

其中代码：
```java
        CoordinatorLayout container = findViewById(R.id.coordinatorLayout);
        CoordinatorLayout.LayoutParams lp = new CoordinatorLayout.LayoutParams(-1, -1);
        // 设置behavior属性 和 ToolBar属性里设置 layout_scrollFlags="scroll|enterAlways"
        lp.setBehavior(new AppBarLayout.ScrollingViewBehavior());
        NestedScrollWebView nestedScrollWebView = new NestedScrollWebView(this);
        byWebView = ByWebView
                .with(this)
                .setWebParent(container, 1, lp)
                .setCustomWebView(nestedScrollWebView)// 设置自定义WebView
                .useWebProgress(ContextCompat.getColor(this, R.color.coloRed))
                .setOnTitleProgressCallback(onTitleProgressCallback)
                .setOnByWebClientCallback(onByWebClientCallback)
                .addJavascriptInterface("injectedObject", new MyJavascriptInterface(this))
                .loadUrl(mUrl);
```

xml文件：
```java
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/coordinatorLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize">

        <android.support.v7.widget.Toolbar
            android:id="@+id/title_tool_bar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="@color/colorPrimary"
            app:contentInsetStartWithNavigation="0dp"
            app:layout_scrollFlags="scroll|enterAlways"
            app:navigationContentDescription="返回"
            app:navigationIcon="@drawable/icon_back"
            app:popupTheme="@style/ThemeOverlay.AppCompat.Light"
            app:theme="@style/ToolbarStyle">

            <TextView
                android:id="@+id/tv_gun_title"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:ellipsize="marquee"
                android:singleLine="true"
                android:textColor="@color/colorWhite"
                android:textSize="18sp"
                android:visibility="visible" />

        </android.support.v7.widget.Toolbar>
    </android.support.design.widget.AppBarLayout>

</android.support.design.widget.CoordinatorLayout>
```

具体可见Demo：[CoordinatorWebActivity](https://github.com/youlookwhat/ByWebView/blob/master/app/src/main/java/com/example/jingbin/webviewstudy/ui/CoordinatorWebActivity.java)

有什么问题再说哈~

**Comment by Para123123** [comment]
好的 谢谢

**Comment by youlookwhat** [comment]
有试过可以用吗

**Comment by Para123123** [comment]
可以用的 非常赞 网页也不会不协调

**Comment by youlookwhat** [comment]
哈哈，那就好
