### ISSUE TITLE
你好，打开爱奇艺详细页闪退？会不会是该库造成的

### ISSUE THREAD

**Issue by stytooldex** [youlookwhat/WebViewStudy#24]
希望大佬给个回复！

**Comment by youlookwhat** [comment]
能不能把对应的那个详情页发出来我用在demo里看看，或者你自己测测就知道了啊

**Comment by stytooldex** [comment]
> 能不能把对应的那个详情页发出来我用在demo里看看，或者你自己测测就知道了啊
> 

https://m.iqiyi.com/v_u7ik3ppd6g.html#vfrm=30-26-15-7

**Comment by youlookwhat** [comment]
抱歉，应该是的，由于request.grant(request.getResources());导致的，我现在删除了发一版。

**Comment by youlookwhat** [comment]
已上传最新版本，抱歉，引用最新的即可:

`implementation 'com.github.youlookwhat:ByWebView:1.1.3'`
