### ISSUE TITLE
用腾讯内核播放视频点击播放按钮还要转圈很久才加载完视频，点击全屏会黑屏一会，返回的时候视频会暂停，继续加载

### ISSUE THREAD

**Issue by CeciliaKasumi** [youlookwhat/WebViewStudy#25]

**Comment by youlookwhat** [comment]
"用腾讯内核播放视频点击播放按钮还要转圈很久才加载完视频，点击全屏会黑屏一会"这个应该是依据视频而定，我刚用爱奇艺的简短的视频尝试，发现速度还可以，没有说很久，应该是部分视频是这样。

“返回的时候视频会暂停，继续加载”这个一直是这样的，没什么问题。

话说这些应该是webview自己处理的，我们这样一般不会处理，我这边没做处理。

**Comment by youlookwhat** [comment]
"用腾讯内核播放视频点击播放按钮还要转圈很久才加载完视频，点击全屏会黑屏一会"这个应该是依据视频而定，我刚用爱奇艺的简短的视频尝试，发现速度还可以，没有说很久，应该是部分视频是这样。

“返回的时候视频会暂停，继续加载”这个一直是这样的，没什么问题。

话说这些应该是webview自己处理的，我们这样一般不会处理，我这边没做处理。
