### ISSUE TITLE
错误页面问题

### ISSUE THREAD

**Issue by AnAnKK** [youlookwhat/WebViewStudy#26]
在已打开的网页中,再次点击的错误页面还是系统的

**Comment by youlookwhat** [comment]
错误页面是那种形式的呢，404吗，还是500，或者无网络

**Comment by AnAnKK** [comment]
是无网络的;我的操作是在一个已打开网页,切断网络就出现了               
网页无法打开 位于:https:....   net::ERR_INTERNET_DISCONNECTED;

**Comment by youlookwhat** [comment]
链接是公开的吗，能不能发出来试试，我这边打开百度然后关掉网络再点击，会出现错误页面。。

**Comment by AnAnKK** [comment]
可能我说的不清楚,  您先打开百度,然后断网,然后点击百度内的链接显示的是系统的错误页面呢,

**Comment by youlookwhat** [comment]
我就是这样试的

**Comment by AnAnKK** [comment]
您更新代码了吗,我昨天下午下载的您写的代码测试的

**Comment by youlookwhat** [comment]
我看到了，在返回的时候可以看到。之前遇到过，我感觉是百度自己处理了错误页面，底部还有“网络不给力，请稍后重试”，这种情况不太好捕获

**Comment by AnAnKK** [comment]
好像是,就百度这个样子的呢
