### ISSUE TITLE
页面重新加载问题

### ISSUE THREAD

**Issue by mason1799** [youlookwhat/WebViewStudy#27]
具体场景：登录成功后获取缓存中的token网页重新加载

参数url()需要重新生成，用loadurl会新起一个页面，用reload不能传参数
byWebView.getWebView().loadUrl(url());

byWebView.getWebView().reload();

**Comment by youlookwhat** [comment]
没太明白，具体是什么问题，或者我这边该怎么修改呢？

**Comment by mason1799** [comment]
重新加载，需要传入url的，同时栈里没有之前网页的，应该怎么做哈？

**Comment by mason1799** [comment]
另外问一下作者哈：设置了.setErrorLayout(R.layout.layout_error_webview, "无法打开网页")
有些网页错误类型没监控到，比如net::ERR_TUNNEL_CONNECTION_FAILED，显示了webview自带的错误页面

**Comment by youlookwhat** [comment]
> 重新加载，需要传入url的，同时栈里没有之前网页的，应该怎么做哈？

你拿的不是最初传进去的url重新加载的吗？

**Comment by youlookwhat** [comment]
> 另外问一下作者哈：设置了.setErrorLayout(R.layout.layout_error_webview, "无法打开网页")
> 有些网页错误类型没监控到，比如net::ERR_TUNNEL_CONNECTION_FAILED，显示了webview自带的错误页面

是的，有一些情况确实比较难监控到它的错误状态，这个需要再处理一下。

**Comment by mason1799** [comment]
@youlookwhat url里有拼接的值需要更新，我用的loadurl重新请求，不过这样会新增一个网页页面，这样是不是用完loadurl，同时再clearhistory？试了不管用

**Comment by mason1799** [comment]
> > 另外问一下作者哈：设置了.setErrorLayout(R.layout.layout_error_webview, "无法打开网页")
> > 有些网页错误类型没监控到，比如net::ERR_TUNNEL_CONNECTION_FAILED，显示了webview自带的错误页面
> 
> 是的，有一些情况确实比较难监控到它的错误状态，这个需要再处理一下。

嗯

**Comment by youlookwhat** [comment]
> @youlookwhat url里有拼接的值需要更新，我用的loadurl重新请求，不过这样会新增一个网页页面，这样是不是用完loadurl，同时再clearhistory？试了不管用

你试过在`doUpdateVisitedHistory `这里清除没？https://www.jianshu.com/p/ab1191fba4ab
