### ISSUE TITLE
建议新增一个webView.postUrl()的入口.

### ISSUE THREAD

**Issue by EternalPlan** [youlookwhat/WebViewStudy#28]
如果需要调用WebView的postUrl的时候,没有入口.
只能调用   byWebView.loadUrl(url).getWebView().postUrl(xxx).
这样写有问题.本身就调用loadUrl()一次,然后再去postUrl()一次.

建议在ByWebView的Builder里面新增一个方法postUrl(String url, byte[] postData).

public ByWebView postUrl(String url, byte[] postData) {
            ByWebView byWebView = new ByWebView(this);
            byWebView.getWebView().postUrl(url, postData);
            return byWebView;
}

**Comment by youlookwhat** [comment]
可以，好提议，我加一下；你可以提交代码，我合并一下

**Comment by youlookwhat** [comment]
你好，不好意思，一直没有回复，很早就处理了，你可以使用 `get()`直接得到ByWebView了，不用loadUrl或者是postUrl
```
        byWebView = ByWebView
                .with(this)
                .setWebParent(container, new LinearLayout.LayoutParams(-1, -1))
                .useWebProgress(ContextCompat.getColor(this, R.color.coloRed))
                .setOnTitleProgressCallback(onTitleProgressCallback)
                .setOnByWebClientCallback(onByWebClientCallback)
                .addJavascriptInterface("injectedObject", new MyJavascriptInterface(this))
                .get();
```
