### ISSUE TITLE
大佬，用Webview网页点击播放视频时，该怎么调用自定义视频播放器播放，可以给我一个思路吗？

### ISSUE THREAD

**Issue by YangChenDong** [youlookwhat/WebViewStudy#31]

**Comment by youlookwhat** [comment]
可以这样，如果是自己公司写的h5，可以在网页里不写视频的样式，写成一个图片的样式或者其他看起来像视频的样式，然后在那个样式上加一个事件，让js调用原生的视频播放器，传对应的视频链接过去。

**Comment by YangChenDong** [comment]
@youlookwhat 大佬，请问像uc等市面上大多数浏览器那样，用户点击网页视频的时候弹出他们自定义的视频播放器，实现思路是怎样的？我们公司要求搞一个类似的，我但不知道实现原理

**Comment by youlookwhat** [comment]
上面那个是常见的思路，还有一种复杂一点，感觉和你说的这种很像，之前有人写过，我觉得uc差不多是这种，当然这待验证，你可以看看，找找思路：
[Android自定义WebView实现Youtube网络视频播放控件](https://blog.csdn.net/lvshaorong/article/details/52082800)

**Comment by YangChenDong** [comment]
@youlookwhat 好的谢谢大佬
