### ISSUE TITLE
示例app输入网址时跳转出错

### ISSUE THREAD

**Issue by nICEnnnnnnnLee** [youlookwhat/WebViewStudy#33]
`ByWebTools.getUrl(String url)`存在问题，当url以http开头时返回空字符串。  
这导致输入网址时老是跳到你这个项目来😳
https://github.com/youlookwhat/ByWebView/blob/fb1fad2626deab8ba35cbed7aad95fb7e4e7979a/ByWebView/src/main/java/me/jingbin/web/ByWebTools.java#L144-L167

**Comment by youlookwhat** [comment]
感谢提出并修复哈
