### ISSUE TITLE
旋转屏幕软键盘问题

### ISSUE THREAD

**Issue by wanhuo** [youlookwhat/WebViewStudy#35]
打开网页，点击会进入全屏横屏模式，此时输入法还是竖屏

**Comment by youlookwhat** [comment]
能不能录个屏，我想象不到是什么场景

**Comment by wanhuo** [comment]
https://user-images.githubusercontent.com/7056314/134626568-b9eedab3-32f5-44a9-8bb6-43318ffbda0c.mp4

**Comment by wanhuo** [comment]
> 能不能录个屏，我想象不到是什么场景

**Comment by youlookwhat** [comment]
这个游戏是一个网页游戏吗，能不能把链接给我试试，或者我用demo里的百度搜索，把它弄成横屏输入，你看是不是符合场景

**Comment by youlookwhat** [comment]
我遇到过你这种情况，我们公司的人开发h5的时候遇到过。
他们是不小心触发了`onShowCustomView`这个方法，但这个一般是打开视频的时候才会触发。你这边应该是不小心触发了`onHideCustomView`，这个应该是视频播放退出才会触发，但是不知道为什么会触发。

我可以做一个方法，禁用掉这个方法的调用，不过你们最好是分析到为什么会触发是不是做了特别的处理

**Comment by youlookwhat** [comment]
最好是把链接给我测试一下，不然我不知道这种方法是否可行 @wanhuo

**Comment by youlookwhat** [comment]
这样处理后，屏幕就在视频全屏播放后退出时，不会再竖屏了

**Comment by youlookwhat** [comment]
依赖最新的版本
```
implementation 'com.github.youlookwhat:ByWebView:1.1.5'
```
然后在打开网页前设置`byWebView.setFixScreenPortrait(true);`试试

**Comment by wanhuo** [comment]
js调用了设置全屏会引发这个问题，辛苦辛苦
