### ISSUE TITLE
进度条bug

### ISSUE THREAD

**Issue by Fcukcpp** [youlookwhat/WebViewStudy#36]
网页加载完了 进度条还在vue的网站
![image](https://user-images.githubusercontent.com/66298978/142711270-64c87f42-5cc8-4a40-a39a-7bb907202da2.png)

**Comment by youlookwhat** [comment]
能把那个链接给我吗，我调试下，或者发个录屏我看看~

**Comment by youlookwhat** [comment]
没有贴具体的链接，我也复现不了，这个先关了。


以后贴问题请带上必要的信息
