### ISSUE TITLE
不支持Androidx吗？

### ISSUE THREAD

**Issue by uaoan** [youlookwhat/WebViewStudy#37]
不支持Androidx吗？

**Comment by youlookwhat** [comment]
支持呀，在CloudReader这个Androidx项目里就是使用的它；可能demo里不是的，那我把demo也换成Androidx版本吧

**Comment by youlookwhat** [comment]
@uaoan 项目已全部升级到Androidx，可引用最新的代码，或者直接下载项目：
`implementation 'com.github.youlookwhat:ByWebView:1.2.0'`

有什么问题再提~
