### ISSUE TITLE
示例APP切换到后台，再次打开时，会自动返回起始页

### ISSUE THREAD

**Issue by KennyLeung** [youlookwhat/WebViewStudy#39]
比如从起始页打开 百度 ，点击Hom键切换到后台，再点击APP切换回前台，显示出来的不再是百度，而是起始页。

**Comment by youlookwhat** [comment]
是的  我看看哈

**Comment by youlookwhat** [comment]
代码已经推送了，并上传了一个新版本哈，

点击下载：https://github.com/youlookwhat/download/blob/main/ByWebView.apk?raw=true

**Comment by KennyLeung** [comment]
> 代码已经推送了，并上传了一个新版本哈，
> 
> 点击下载：https://github.com/youlookwhat/download/blob/main/ByWebView.apk?raw=true

感谢。经测试，问题已经解决。
