### ISSUE TITLE
ByWebView.java 是否有错误？

### ISSUE THREAD

**Issue by KennyLeung** [youlookwhat/WebViewStudy#40]
文件 https://github.com/youlookwhat/ByWebView/blob/master/ByWebView/src/main/java/me/jingbin/web/ByWebView.java 中 198行：
    public void onPause() {
        mWebView.onPause();
        mWebView.resumeTimers();
    }
是否应为：
mWebView.pauseTimers();

**Comment by youlookwhat** [comment]
应该是的，感谢提出，我修正一下~❤️
