### ISSUE TITLE
有時候會出現第二個灰色進度條

### ISSUE THREAD

**Issue by ivanisidrowu** [youlookwhat/WebViewStudy#41]
作者你好，

我發現有時候讀取網頁會出現第二條灰色進度條，而且沒辦法改顏色。
請參考下面的圖：

<img width="427" alt="Screen Shot 2022-01-27 at 2 13 40 PM" src="https://user-images.githubusercontent.com/6141401/151304637-0d6bcce4-0c22-49fd-8a1c-33904495f2f5.png">

<img width="428" alt="Screen Shot 2022-01-27 at 2 13 57 PM" src="https://user-images.githubusercontent.com/6141401/151304666-a657be6b-afec-485b-81d4-33f7baafac62.png">

<img width="425" alt="Screen Shot 2022-01-27 at 2 14 08 PM" src="https://user-images.githubusercontent.com/6141401/151304687-ffaf737a-41fe-4630-9a7b-9b83899f9efa.png">

想請問有沒有方法可以移除第二個進度條？或是改它的顏色呢？
謝謝！

程式碼：
```kotlin
private fun initWebView() {
        byWebView = ByWebView
            .with(this)
            .useWebProgress(getColor(R.color.red500))
            .setWebParent(
                binding.container,
                FrameLayout.LayoutParams(
                    ViewGroup.LayoutParams.MATCH_PARENT,
                    ViewGroup.LayoutParams.MATCH_PARENT
                )
            )
            .setOnTitleProgressCallback(titleCallback)
            .setOnByWebClientCallback(byWebClientCallback)
            .loadUrl(currentUrl)
    }
```

**Comment by youlookwhat** [comment]
我觉得这应该是网页自带的进度条，你不设置进度条试试，看还会不会显示进度条。
可以把对应的网页链接贴一下，我看看。

**Comment by ivanisidrowu** [comment]
原來如此，我發現的確是網頁本身的進度條，感謝回覆！
