### ISSUE TITLE
腾讯X5内核并没有调用成功

### ISSUE THREAD

**Issue by KennyLeung** [youlookwhat/WebViewStudy#42]
据腾讯TBS接口文档介绍，X5内核中的 webview 是兼容原生 webview 的，当X5内核没有成功调用时，会自动以原生webview代替。

证据：使用X5内核打开网页时，选择网页上的文字会显示两个水滴状的选择器，如下图：
![图片](https://user-images.githubusercontent.com/4188953/154834162-8f28e524-2e3b-4c5a-ba5f-72e5987825b7.png)

本项目中选择腾讯X5内核后，打开的网页如下图，选择器不是水滴状的：
![图片](https://user-images.githubusercontent.com/4188953/154834210-24a0c5ec-3c1c-4d8f-8655-9fd13926a6c3.png)
![图片](https://user-images.githubusercontent.com/4188953/154834216-1564385f-c3d6-44a9-803d-c0169ffc7a13.png)

所以，本项目中的腾讯X5内核并没有成功调用。
这里发一个能够成功使用腾讯X5内核的示例项目作参考：
https://github.com/daleige/AndroidSamples/tree/master/TBSDemo

**Comment by youlookwhat** [comment]
你的Android系统是多少，我这边用 oppo findx3 pro android11是可以成功的，我再检查一下

**Comment by youlookwhat** [comment]
我加了一个“非wifi条件下允许下载X5内核”，你可以再试试

**Comment by youlookwhat** [comment]
4g也可以下载腾讯X5内核
