### ISSUE TITLE
既然用了腾讯内核，建议向SuperWeb一样，加上浏览PDF/PPT/DOC/EXCEL/TXT等文件的功能

### ISSUE THREAD

**Issue by NanyangTaiji** [youlookwhat/WebViewStudy#45]
[SuperWeb](https://github.com/Victory-Over/SuperWeb)
Android基于腾讯X5内核的WebView(超级浏览器)，拥有文件上传、下载、浏览（支持PDF/PPT/DOC/EXCEL/TXT格式）、Android与JS的交互、视频播放、自定义进度条、下拉回弹等功能.

**Comment by youlookwhat** [comment]
项目里用到了腾讯X5内核，但是是给一个demo，而作为依赖引入的是系统webview的内核。

我可以加上浏览（支持PDF/PPT/DOC/EXCEL/TXT格式）的功能，至于上传、下载大部分还是要依赖与原生交互来实现，因为会涉及到文件权限，这个就暂时不考虑了

**Comment by NanyangTaiji** [comment]
> 项目里用到了腾讯X5内核，但是是给一个demo，而作为依赖引入的是系统webview的内核。
> 
> 我可以加上浏览（支持PDF/PPT/DOC/EXCEL/TXT格式）的功能，至于上传、下载大部分还是要依赖与原生交互来实现，因为会涉及到文件权限，这个就暂时不考虑了

非常好，期盼着。

**Comment by NanyangTaiji** [comment]
You 什么进展吗？

**Comment by youlookwhat** [comment]
抱歉，这个忘记了~
节后(或者节中)会加上浏览pdf，有最新的消息会第一时间在这里回复的。

**Comment by eric-gitta-moore** [comment]
期待+1

**Comment by youlookwhat** [comment]
暂时不会添加pdf浏览功能：有2个原因：
1、项目是基于原生webview做的封装，不是腾讯的webview，腾讯的很好实现而原生的实现比较麻烦，SuperWeb是基于腾讯webview的。
2、现在已经有成熟的pdf预览方案，且已开源[AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer)，没必要重新造轮子。

如有需要，请使用：[AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer)

**Comment by youlookwhat** [comment]
@NanyangTaiji @james-curtis

**Comment by eric-gitta-moore** [comment]
那文件下载功能可以添加一下吗？下载时候直接调用系统的下载

**Comment by youlookwhat** [comment]
> 那文件下载功能可以添加一下吗？下载时候直接调用系统的下载

下载是app的一个功能模块，其实和webview无关。
例如下载视频，正规点是h5调用原生的方法，将视频链接传过来，然后再去下载。至于怎么实现，可以参考一些优秀的三方下载库。

**Comment by NanyangTaiji** [comment]
Webview 浏览pdf 的 js 有的是，建议你加上这个功能只是希望你进一步完善你这个package。
https://github.com/GrapheneOS/PdfViewer

**Comment by youlookwhat** [comment]
谢谢你的建议，短时间里不会完善：
1、完善也是使用[AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer)，你可以直接使用它。
2、我现在有更重要的事情做，这件事没那么紧急。我更希望你来完善下，非常高兴你来提交代码。
