### ISSUE TITLE
图片长按监听问题

### ISSUE THREAD

**Issue by super963883929** [youlookwhat/WebViewStudy#46]
我重写了
                  `.addJavascriptInterface("injectedObject", new MyJavascriptInterface(this){
                            /**
                            * 前端代码嵌入js：
                            * imageClick 名应和js函数方法名一致
                            *
                            * @param src 图片的链接
                            */
                            @Override
                             public void imageClick(String src) {
                                 super.imageClick(src);
                                 Toast.makeText(ByWebViewActivity.this, src, Toast.LENGTH_SHORT).show();
                             }

             
                      })`
无法回调问题,

**Comment by youlookwhat** [comment]
长按图片监听是这个：
```
webView.setOnLongClickListener(new View.OnLongClickListener() {
            @Override
            public boolean onLongClick(View v) {
                return handleLongImage();
            }
        });
```
你找找demo里这个代码。

你上面的代码是给图片设置点击事件的js，然后点击图片的时候触发的。

**Comment by super963883929** [comment]
可以了可以了,谢谢大佬

> 长按图片监听是这个：
> 
> ```
> webView.setOnLongClickListener(new View.OnLongClickListener() {
>             @Override
>             public boolean onLongClick(View v) {
>                 return handleLongImage();
>             }
>         });
> ```
> 
> 你找demo里这个代码。
> 
> 你的代码是给设置点击事件的，然后点击图片的时间触发的js。

可以了可以了,谢谢大佬

**Comment by youlookwhat** [comment]
可以了就好哈，有问题再提。

**Comment by super963883929** [comment]
> 可以了就好哈，有问题再提。

好的好的

**Comment by super963883929** [comment]
对了,还得麻烦你一下,就是有没有可以遍历所有html标签里面的图片方法呢?我想实现一个看图模式

**Comment by youlookwhat** [comment]
这里是遍历所有的<img标签，我觉得你可以根据这段代码，看怎么处理一下然后符合你的需求：
```
    /**
     * 前端注入JS：
     * 这段js函数的功能就是，遍历所有的img节点，并添加onclick函数，函数的功能是在图片点击的时候调用本地java接口并传递url过去
     */
    private void loadImageClickJS() {
        loadJs("javascript:(function(){" +
                "var objs = document.getElementsByTagName(\"img\");" +
                "for(var i=0;i<objs.length;i++)" +
                "{" +
                "objs[i].onclick=function(){window.injectedObject.imageClick(this.getAttribute(\"src\"));}" +
                "}" +
                "})()");
    }
```

**Comment by super963883929** [comment]
我用这个解决了

    /***
     * 遍历所有图片
     */
    public void addLocalJs() {
        webView.loadUrl("javascript:(function(){ " + "var objs = document.getElementsByTagName(\"img\");"
                + " var array=new Array(); " + " for(var j=0;j<objs.length;j++){ " + "array[j]=objs[j].src;" + " }  "
                + "window.injectedObject.getImage(array);   })()");
    }`



`

**Comment by super963883929** [comment]
不管怎么样还是谢谢了

**Comment by youlookwhat** [comment]
> 我用这个解决了
> 
> ```
> /***
>  * 遍历所有图片
>  */
> public void addLocalJs() {
>     webView.loadUrl("javascript:(function(){ " + "var objs = document.getElementsByTagName(\"img\");"
>             + " var array=new Array(); " + " for(var j=0;j<objs.length;j++){ " + "array[j]=objs[j].src;" + " }  "
>             + "window.injectedObject.getImage(array);   })()");
> }`
> ```
> 
> `

恩恩  我也是这个意思，解决了就好
