### ISSUE TITLE
老是弹出记住密码~

### ISSUE THREAD

**Issue by FuYu520** [youlookwhat/WebViewStudy#48]
想请教一个问题，我关闭了记住密码和表单数据 webSetting.setSaveFormData(false)和 webSetting.setSavePassword(false);
![image](https://user-images.githubusercontent.com/44915609/174207690-c08a3996-2f39-4300-be31-92ccaea6770a.png)

**Comment by FuYu520** [comment]
还是会弹出，请问大佬知道这是因为啥嘛

**Comment by youlookwhat** [comment]
这个是不是网页自己的逻辑，与你设置这个无关

**Comment by FuYu520** [comment]
谢谢作者回答，网页没有这个逻辑的，就很奇怪~，明明设置了，却没生效，有时候会弹，有时候不弹，我再研究一下吧
