### ISSUE TITLE
如果webview的父控件是SwipeRefreshLayout，那么滑动会有冲突，应该怎么去解决呢

### ISSUE THREAD

**Issue by chengzhuangjie** [youlookwhat/WebViewStudy#49]

**Comment by youlookwhat** [comment]
是不太好解决，建议使用下拉刷新框架 [SmartRefreshLayout](https://github.com/scwang90/SmartRefreshLayout)。

或者看看别人的解决方案：[Android SwipeRefreshLayout嵌套Webview滑动冲突问题解决](https://www.jianshu.com/p/dd27f91cd2f4)
