### ISSUE TITLE
如何禁用X5浏览器的自动焦点呢？

### ISSUE THREAD

**Issue by xcdiv** [youlookwhat/WebViewStudy#51]
如果用键盘或者遥控器会自己出来光标的焦点，如何设置禁用呢？您知道吗？

**Comment by youlookwhat** [comment]
给不自动聚焦的view设置这个试试，例如webview
webview.setFocusable(false);
webview.setFocusableInTouchMode(false);

**Comment by youlookwhat** [comment]
有问题再提了
