### ISSUE TITLE
JSBridge demo

### ISSUE THREAD

**Issue by LuMuddy** [youlookwhat/WebViewStudy#52]
JSBridge 似乎无法使用

网页为
`<html><head><title>Android与JS交互实例</title><script type="text/javascript">function aa() {window.WebViewJavascriptBridge.callHandler("testSend", function (responseData) {console.log(responseData)});}</script></head><body><button onClick="aa()">点击调用java代码</button></body></html>`

JAVA使用WVJBWebViewActivity页面
注册
`webView.registerHandler("testSend", (data, callback) -> Log.e("----","----1----"));`
没有收到任何回调

**Comment by youlookwhat** [comment]
是有点问题，我放一个demo上来

**Comment by LuMuddy** [comment]
好的，感谢

**Comment by youlookwhat** [comment]
可以了哈，之前是我的问题，我少传了一个js文件。

放了一个demo，但是没用放 java调用js的示例，我不知道h5里面要怎么写。
加了ja调用java方法的使用示例(和你写的基本是一样的)。

具体见：https://github.com/youlookwhat/ByWebView/commit/fa75890d70cc26fb397a6d27700dc23b4edab3be

**Comment by LuMuddy** [comment]
已经可以，感谢
