### ISSUE TITLE
js，alert会显示网址，这个可以处理下吗

### ISSUE THREAD

**Issue by shapolang** [youlookwhat/WebViewStudy#53]
//响应webview 加载H5页面中的alert函数，否则alert显示不出来
        webView.setWebChromeClient(new WebChromeClient() {
            @Override
            public boolean onJsAlert(WebView view, String url, String message, final JsResult result) {
                AlertDialog.Builder b = new AlertDialog.Builder(ctx);
                b.setTitle("title");
                b.setMessage(message);
                b.setPositiveButton(android.R.string.ok, new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialog, int which) {
                        result.confirm();
                    }
                });
                b.create().show();
                return true;
            }
        });

**Comment by youlookwhat** [comment]
好的   我看看

**Comment by shapolang** [comment]
自动回复
O(∩_∩)O~，亲，邮件已经收到，

**Comment by youlookwhat** [comment]
已处理，并增加了demo，可以看看哈
https://github.com/youlookwhat/ByWebView/commit/aed267ad7a0589a61b28f68a7ba0d263d2d8bb10

**Comment by shapolang** [comment]
> 已处理，并增加了demo，可以看看哈 [aed267a](https://github.com/youlookwhat/ByWebView/commit/aed267ad7a0589a61b28f68a7ba0d263d2d8bb10)

厉害！！！！！

**Comment by shapolang** [comment]
自动回复
O(∩_∩)O~，亲，邮件已经收到，
