### ISSUE TITLE
看了下demo代码，ByWebView是不能直接使用X5吗？

### ISSUE THREAD

**Issue by cikichen** [youlookwhat/WebViewStudy#55]
看了demo的代码，x5的使用纯粹就是标准x5，并没有和bywebview相关，如果现在使用的bywebview，怎么从系统内核切换到x5内核？

**Comment by youlookwhat** [comment]
是的，集成了bywebview还需要单独集成x5，我没有把x5放进去

**Comment by KennyLeung** [comment]
> 是的，集成了bywebview还需要单独集成x5，我没有把x5放进去

建议把x5从示例中彻底移除。主要有两个原因：1、当X5内核下载不成功时，用的其实还是系统的webview；2、x5内核从2023年5月起，已经移除TbsReaderView，不能预览文档，即使旧版也不能。TbsReaderView已变成收费功能。

**Comment by youlookwhat** [comment]
那我是不是更新 x5版本就好了？
引入的byWebView本身就没有x5

**Comment by KennyLeung** [comment]
x5很鸡肋了，项目中真正使用一堆坑，远不如你的ByWebView好用，做好ByWebView足够了。

**Comment by youlookwhat** [comment]
感谢肯定~

**Comment by cikichen** [comment]
> x5很鸡肋了，项目中真正使用一堆坑，远不如你的ByWebView好用，做好ByWebView足够了。

x5最大的优点是国内杂七杂八的设备兼容性，能保证统一的内核，因为很多老设备的浏览器内核非常低还不能升级，会有各种样式问题

**Comment by KennyLeung** [comment]
> > x5很鸡肋了，项目中真正使用一堆坑，远不如你的ByWebView好用，做好ByWebView足够了。
> 
> x5最大的优点是国内杂七杂八的设备兼容性，能保证统一的内核，因为很多老设备的浏览器内核非常低还不能升级，会有各种样式问题

你说的也有道理，x5的兼容性会好不少。不过要兼容大量不同型号设备，一般都是比较大的项目了，在这种项目团队里，通常要有一些带两把刷子的技术大拿，维护一套自己的Webview，指望用x5这种不开源的库，无异于将把柄交给别人。几天前腾讯突然把旧版x5的文档预览功能停掉，导致我的app无法打开文档，被杀了个措手不及，花了两天时间才把PDF预览集成进去。ByWebView一般的应用场合足够了，我测试了多个不同型号的设备，目前还没有遇到不兼容问题。反倒是安卓自己版本的差异，导致每隔一段时间就要升级app。
