### ISSUE TITLE
大佬你好 有个问题想要咨询下

### ISSUE THREAD

**Issue by 756230883** [youlookwhat/WebViewStudy#57]
你好  视频全屏后  退出全屏 发现 webView自动滚动到了 顶部 请问有什么解决方案吗

**Comment by youlookwhat** [comment]
是的，我也发现了，我试试看能不能用
```
webview.setFocusable(false);
webview.setFocusableInTouchMode(false);
```

不行的话就不太好解决了，还要再看看

**Comment by youlookwhat** [comment]
我发现不是全部的视频全屏后都回到了顶部，百度百科里的视频回到了顶部，但是这个链接没有:

https://haokan.baidu.com/v?pd=wisenatural&vid=2097992867917438471&source=

播放这个链接里的视频就是正常的。我觉得这是h5需要处理的问题。

**Comment by 756230883** [comment]
感谢大佬的回复  我现在是点击全屏的时候 记录下WebView滑动的距离 退出全屏的时候 让WebView再滑动到刚刚的位置 暂时只能这么解决

**Comment by youlookwhat** [comment]
恩恩   这也是一个方法~

是不是使用这样的方法，我没有实践过~
```
webview.setOnScrollChangeListener(new View.OnScrollChangeListener() {
    @Override
    public void onScrollChange(View v, int scrollX, int scrollY, int oldScrollX, int oldScrollY) {

    }
});
webview.setScrollY();
```

**Comment by 756230883** [comment]
是的  在监听中获取 y 值  监听退出全屏的时候  在webview.setScrollY(); 给Webview
