### ISSUE TITLE
竖版视频全屏播放

### ISSUE THREAD

**Issue by vivian688** [youlookwhat/WebViewStudy#58]
请问可以根据视频横竖版来处理全屏播放是否为横竖屏吗？现在竖版视频点击全屏，也变成横屏播放了

**Comment by youlookwhat** [comment]
可以的：

---------

可手动处理视频全屏播放时的横竖屏：

在`OnTitleProgressCallback`里增加了`onHandleScreenOrientation(boolean isShow)`
```
    /**
     * 全屏显示时处理横竖屏。
     * 默认返回false，全屏时为横屏，全屏还原后为竖屏
     * 如果要手动处理，需要返回true！
     *
     * @param isShow 是否显示了全屏视频 ture点击了全屏显示，false全屏视频还原
     */
    public boolean onHandleScreenOrientation(boolean isShow) {
        return false;
    }
```

**Comment by youlookwhat** [comment]
1.2.1 版本已增加

**Comment by vivian688** [comment]
> 可以的：
> 
> 可手动处理视频全屏播放时的横竖屏：
> 
> 在`OnTitleProgressCallback`里增加了`onHandleScreenOrientation(boolean isShow)`
> 
> ```
>     /**
>      * 全屏显示时处理横竖屏。
>      * 默认返回false，全屏时为横屏，全屏还原后为竖屏
>      * 如果要手动处理，需要返回true！
>      *
>      * @param isShow 是否显示了全屏视频 ture点击了全屏显示，false全屏视频还原
>      */
>     public boolean onHandleScreenOrientation(boolean isShow) {
>         return false;
>     }
> ```

OK，通过前端返回的标识在该方法内处理了。
