### ISSUE TITLE
图片点击显示

### ISSUE THREAD

**Issue by wukan1986** [youlookwhat/WebViewStudy#6]
您好，能否提供网页完全打开后，点图片的占位符后再显示的图片的功能呢？
类似于网易新闻客户端和知乎的功能呢？
谢谢！

**Comment by youlookwhat** [comment]
你这是网页自己的功能吧？或者是原生的页面

**Comment by wukan1986** [comment]
pc版的ie也可以先禁用图片加载，用户可以点击占位符，右键显示图片

**Comment by youlookwhat** [comment]
是ie自带的功能吗，webview好像没有发现类似的功能，有一个等网页加载完成后再加载网页中图片的功能，但是没有听说过点击了再显示的

**Comment by wukan1986** [comment]
https://jingyan.baidu.com/album/335530daad396619cb41c326.html?picindex=4

两个复选框：显示图片，显示图像下载占位符

**Comment by youlookwhat** [comment]
看到了，这是电脑浏览器的设置。webview有这样的设置吗，我暂时还没发现。
