### ISSUE TITLE
运行在 Andoid11 未适配 Android 分区存储 图片上传会有问题 ，拿不到图片 uri 

### ISSUE THREAD

**Issue by thisfeng** [youlookwhat/WebViewStudy#63]
代码中 在 Android11 以上 访问图片 记得修改一下 访问的方式即可。
 1 、增加分区存储 
 ` <meta-data
            android:name="ScopedStorage"
            android:value="true" />`

2 、使用获取权限  `  <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />`

 3 、拿到权限后 通过此方式访问相册 即可。
`Intent intent = new Intent(Intent.ACTION_PICK,
                MediaStore.Images.Media.EXTERNAL_CONTENT_URI);
        startActivityForResult(intent, REQUEST_CODE_ALBUM);`

**Comment by youlookwhat** [comment]
好的，感谢提出，我修改下~

**Comment by youlookwhat** [comment]
我刚在android14上试了一下，可以正常显示出图片呀。

而且这一块建议是，网页里点击后调用原生的方法，上传成功后再将图片给网页。

**Comment by thisfeng** [comment]
有沒有可能你用的 targetSdkVersion  30  ！太低了 
你設置成 31 或者 更高 咧 33

**Comment by youlookwhat** [comment]
好 我试试

**Comment by youlookwhat** [comment]
换成了31 ，也可以呀、
