### ISSUE TITLE
在Android Pie 上面HTTP链接打不开

### ISSUE THREAD

**Issue by lfork** [youlookwhat/WebViewStudy#8]
环境
OS:Android Pie
Device: OnePlus 6

临时解决方案：
在AndroidManifest.xml文件中的application节点中，配置：android:usesCleartextTraffic=“true”

**Comment by lfork** [comment]
https://developer.android.com/about/versions/pie/android-9.0-changes-28?hl=zh-cn

**Comment by youlookwhat** [comment]
谢谢，暂时还没用Android Pie测试过，马上加上~
