### ISSUE TITLE
720云网页，陀螺仪加速器失效问题

### ISSUE THREAD

**Issue by edifangyi** [youlookwhat/WebViewStudy#9]
例如：https://720yun.com/t/07bju0mukO0?scene_id=22940928，无法使用陀螺仪

**Comment by youlookwhat** [comment]
你是什么机型呢，我用三星s8是好的，点右上角的第三个按钮，就可以移动手机看到，是需要点那个按钮吧，不然没效果

**Comment by edifangyi** [comment]
@youlookwhat  华为，，可以使用，但是乱飞，敏感度特别高，但是使用系统自带的浏览器和第三方比如 QQ浏览器就没有这个事情，
![dlrrn1ne 7oage940 ku3o](https://user-images.githubusercontent.com/12421552/51105077-f3d09a80-1822-11e9-93d4-f152b5ae71d9.jpg)

![image](https://user-images.githubusercontent.com/12421552/51105063-ec10f600-1822-11e9-9830-6de1de3cce3a.png)

**Comment by youlookwhat** [comment]
嗯，发现这个问题了，不太好排查，稍等。

**Comment by youlookwhat** [comment]
我发现腾讯x5内核的浏览器可以，但是系统原生webview的浏览器会抖动。
我已经集成进去了，你可以再下载看看。
下载链接：https://fir.im/webviewstudy

**Comment by edifangyi** [comment]
还是不行，X5内核里  有一个VR 设置，里面没有陀螺仪校验的选项

**Comment by youlookwhat** [comment]
是不是还是跟手机有关系，我用我这个手机打开那个网页转动的时候不抖动

**Comment by edifangyi** [comment]
要不加我QQ 远程用这台手机调试

**Comment by youlookwhat** [comment]
小米3和三星s8是好的，如果其他手机有问题，属于网页兼容问题，建议调试网页~
